<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net8.0;net10.0</TargetFrameworks>
    <RootNamespace>MediaInfo</RootNamespace>
    <Version>$(MediaInfoVersion)</Version>
    <AssemblyVersion>$(MediaInfoFileVersion)</AssemblyVersion>
    <FileVersion>$(MediaInfoFileVersion)</FileVersion>
    <Company>$(PackageCompany)</Company>
    <Authors>$(PackageAuthor)</Authors>
    <Product>MP-MediaInfo</Product>
    <PackageTags>mediainfo;wrapper;dotnet;.net;core</PackageTags>
    <Copyright>$(PackageCopyright)</Copyright>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageProjectUrl>$(PackageRepository)</PackageProjectUrl>
    <PackageLicenseExpression>BSD-2-Clause</PackageLicenseExpression>
    <RepositoryUrl>$(PackageRepository)</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>$(PackageIconValue)</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>$(PackageDescription)</Description>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <!--<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>-->
  </PropertyGroup>
    
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>$(MSBuildProjectName).Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>MediaInfo.Analysis.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>MediaInfo.Analysis.Integration.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(Net8x)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(Net8x)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(Net8x)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(Net8x)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(Net10x)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(Net10x)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="$(GitHub)" PrivateAssets="All" />
    <PackageReference Include="MediaInfo.Core.Native" Version="$(CoreNative)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="images/$(PackageIconValue)" Pack="true" PackagePath="" />
    <Compile Remove="ILogger.cs" />
    <Compile Remove="Extensions\LogExtensions.cs" />
    <None Include="..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\docs\nuget\MediaInfo.Wrapper.Core.md" Pack="true" PackagePath="README.md" />
  </ItemGroup>

</Project>