version: '26.10.{build}'

image: Visual Studio 2022
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

environment:
  matrix:
  - solution_name: MP-MediaInfo.sln
    test_project: MediaInfo.Wrapper.Tests.csproj
  - solution_name: MP-MediaInfo.Core.sln
    test_project: MediaInfo.Wrapper.Core.Tests.csproj

install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '10.0.103' -InstallDir "$env:ProgramFiles\dotnet"

before_build:
- cmd: >-
    dotnet restore %SolutionName%

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: msbuild %SolutionName% /verbosity:minimal /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- cmd: >-
    dotnet test .\MediaInfo.Wrapper.Tests\%test_project% /p:Configuration=Release

artifacts:
- path: .\MediaInfo.Wrapper\bin\Release\*.nupkg
  name: package
- path: .\MediaInfo.Wrapper\bin\Release\*.snupkg
  name: 'debug package'