<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <GitHub>8.0.0</GitHub>
    <CoreNative>26.10.0</CoreNative>
    <Native>26.10.0</Native>
    <TestSdk>17.14.1</TestSdk>
    <MoqLib>4.20.72</MoqLib>
    <Net8x>8.0.*</Net8x>
    <Net10x>10.0.*</Net10x>
    <AzureContainer>1.23.0</AzureContainer>
    <FluentAssertions>7.2.*</FluentAssertions>
    <MapsterLib>7.4.0</MapsterLib>
    <MapsterDILib>1.0.1</MapsterDILib>
    <xUnitRunner>3.1.5</xUnitRunner>
    <xUnit>2.9.1</xUnit>
    <MediaToolkitNet>0.3.1</MediaToolkitNet>
    <Scalar>2.17.4</Scalar>
    <FFmpeg>20260918.1.0</FFmpeg>
    <CsvHelper>33.1.0</CsvHelper>
    <MediaInfoVersion>26.10.0</MediaInfoVersion>
    <MediaInfoFileVersion>26.10.0.0</MediaInfoFileVersion>
    <PackageAuthor>yartat</PackageAuthor>
    <PackageCompany>Yaroslav Tatarenko</PackageCompany>
    <PackageRepository>https://github.com/yartat/MP-MediaInfo</PackageRepository>
    <PackageCopyright>Copyright © 2017-2026 Yaroslav Tatarenko</PackageCopyright>
    <PackageDescription>MediaInfo(Lib) is a convenient unified display of the most relevant technical and tag data for video and audio files.
MediaInfo .NET wrapper with support network AV streams.</PackageDescription>
    <PackageIconValue>MediaInfo_90x90.png</PackageIconValue>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
