<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <GitHub>8.0.0</GitHub>
    <CoreNative>26.1.0</CoreNative>
    <Native>26.5.0</Native>
    <TestSdk>17.14.1</TestSdk>
    <MoqLib>4.20.72</MoqLib>
    <Net8x>8.0.*</Net8x>
    <Net10x>10.0.*</Net10x>
    <AzureContainer>1.23.0</AzureContainer>
    <FluentAssertions>7.2.*</FluentAssertions>
    <MapsterLib>7.4.0</MapsterLib>
    <MapsterDILib>1.0.1</MapsterDILib>
    <xUnitRunner>3.1.5</xUnitRunner>
    <xUnit>2.9.1</xUnit>
    <Swashbuckle>10.1.4</Swashbuckle>
    <CsvHelper>33.1.0</CsvHelper>
    <MediaInfoVersion>26.5.0</MediaInfoVersion>
    <MediaInfoFileVersion>26.5.0.0</MediaInfoFileVersion>
    <PackageAuthor>yartat</PackageAuthor>
    <PackageCompany>Yaroslav Tatarenko</PackageCompany>
    <PackageRepository>https://github.com/yartat/MP-MediaInfo</PackageRepository>
    <PackageCopyright>Copyright © 2017-2026 Yaroslav Tatarenko</PackageCopyright>
    <PackageNotes>Copyright © 2017-2026 Yaroslav Tatarenko

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.</PackageNotes>
    <PackageDescription>MediaInfo(Lib) is a convenient unified display of the most relevant technical and tag data for video and audio files.
MediaInfo .NET wrapper with support network AV streams.</PackageDescription>
    <PackageIconValue>MediaInfo_90x90.png</PackageIconValue>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
