<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>MediaInfo.Analysis.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="$(MoqLib)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(Net10x)" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="$(Net10x)" />
    <PackageReference Include="FluentAssertions" Version="$(FluentAssertions)" />

    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdk)" />
    <PackageReference Include="xunit" Version="$(xUnit)" />
    <PackageReference Include="xunit.extensibility.execution" Version="$(xUnit)" />

    <PackageReference Include="xunit.runner.visualstudio" Version="$(xUnitRunner)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediaInfo.Wrapper\MediaInfo.Wrapper.Core.csproj" />
  </ItemGroup>

</Project>
